export const messages = {
  FILE_CONFIRM_UPLOAD_FAILED: 'Upload confirmation failed. Try again',
  FILE_UPLOAD_FAILED: 'Upload failed. Try again',
  EXTENSION_NOT_SUPPORTED: 'File not supported',
  GET_FILE_UPLOAD_URL_FAILED: 'Get upload url failed, try again.'
};

export const events = {
  FOLDER_CREATED: "FOLDER_CREATED",
  FOLDER_CREATE_FAILED: "FOLDER_CREATE_FAILED",
  FILE_UPLOAD_INITIATED: "FILE_UPLOAD_INITIATED",
  GET_FILE_UPLOAD_URL_FAILED: "GET_FILE_UPLOAD_URL_FAILED",
  FILE_UPLOAD_PROGRESS: "FILE_UPLOAD_PROGRESS",
  FILE_UPLOAD_COMPLETED: "FILE_UPLOAD_COMPLETED",
  ALL: "ALL"
};

export const UploaderEvents = {
  UPLOAD_INITIATED: "UPLOAD_INITIATED",
  UPLOAD_PROGRESS: "UPLOAD_PROGRESS",
  UPLOAD_COMPLETED: "UPLOAD_COMPLETED",
  UPLOAD_FAILED: "UPLOAD_FAILED",
  CHUNK_UPLOAD_PROGRESS: "CHUNK_UPLOAD_PROGRESS",
  CHUNK_UPLOAD_COMPLETED: "CHUNK_UPLOAD_COMPLETED",
  CHUNK_UPLOAD_FAILED: "CHUNK_UPLOAD_FAILED",
}
